version: "3.9"

services:
  postgres:
    image: "postgres:14"
    container_name: "crud-postgres"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=Ahrilovescat1@"
      - "POSTGRES_DB=Kata"

  app:
    image: "postgres:14"
    build: ./
    container_name: "java-app"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=Ahrilovescat1@"
      - "POSTGRES_DB=Kata"
    ports:
      - "8080:8080"